version: '3.1'

volumes:
  labhive_mongodb_stagingDB:
    external: true
  labhive_mongodb_stagingConfig:
    external: true

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - labhive_mongodb_stagingDB:/data/db
      - labhive_mongodb_stagingConfig:/data/configdb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: labhive
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

