version: '3.7'

services:
  redis:
    image: redis
    restart: always
    networks:
      - network

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_DB:/data/db
      - mongodb_Config:/data/configdb
    networks:
      - network
  
  app:
    image: labhive/labhive:${TAG:-staging}
    restart: always
    depends_on: 
      - mongodb
    build:
      context: .
      args:
        enableDev: 'true'
        staging: 'true'
    ports:
      - "5000"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        delay: 5s
      update_config:
        parallelism: 1
        delay: 5s
        monitor: 30s
      rollback_config:
        parallelism: 0
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.to-LabHive-${ENV:-Staging}.rule=Host(`${DOMAIN:-}dev.labhive.de`)"
        - "traefik.http.services.LabHive-${ENV:-Staging}.loadbalancer.server.port=5000"
        - "traefik.docker.lbswarm=true"
    environment: 
      STAGING: "1"
      DISABLE_DISCORD_BOT: "0"
      BASE_URL: "https://${DOMAIN:-}dev.labhive.de"
    networks:
      - network
      - traefik
    volumes: 
      - secret:/app/secret


volumes:
  mongodb_DB:
  mongodb_Config:
  secret:


networks:
  network:
    driver: overlay
    attachable: true
  traefik:
    external: true
