on: push

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "LabHive/LabHive"
          ref: "dev"
          token: "${{ labhive_pat }}"