name: "Staging"
on:
  push:
    branches:
      - dev
    paths:
      - 'labshare-client/**'
      - '.github/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: cd labshare-client && npm install
      - run: cd labshare-client && npm run build


  docker:
    name: "Prepare Docker"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: "Build and Push Docker Image"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: labhive/labhive:staging
          context: ./labshare-client
          build-args: |
            enableDev=true
            staging=true
          
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: "Deploy"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd LabHive-Staging/labshare-client;
            git reset --hard;
            git pull;
            git submodule update --init;

            ./deploy.sh Staging

  notify:
    name: "Notify"
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify Discord
        run: |
          curl -X "POST" "${{ secrets.DISCORD_WEBHOOK_RELEASE }}" \
            -H 'Content-Type: application/json' \
            -d $'{
          "username": "BizzyB",
          "embeds": [
            {
              "author": {
                "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                "name": "GitHub"
              },
              "title": "New Staging Release available",
              "description": "Changelog: ${{ github.event.compare }}\\nAvailable at: https://dev.labhive.de",
              "url": "${{ github.event.compare }}"
            }
          ]
          }'
