name: "PullRequest"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - master
    paths:
      - 'labshare-client/**'
      - '.github/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
      - run: cd labshare-client && npm install
      - run: cd labshare-client && npm run build


  prepare:
    name: "Prepare"
    if: contains("[DEPLOY]", github.event.pull_request.title)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: "Copy folder to server"
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          ARGS: -avzr --delete
          TARGET: /home/${{ secrets.USERNAME }}/LabHive_${{ github.event.pull_request.head.ref }}

  deploy:
    name: "Deploy"
    if: contains("[DEPLOY]", github.event.pull_request.title)
    runs-on: ubuntu-latest
    needs: prepare
    env:
      BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: "Deploy"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd LabHive_${BRANCH}/labshare-client;
            ./deploy.sh ${BRANCH}

  notify:
    name: "Notify"
    if: contains("[DEPLOY]", github.event.pull_request.title)
    runs-on: ubuntu-latest
    needs: deploy
    env:
      BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Automatically deployed to [${BRANCH}.dev.labhive.de](https://${BRANCH}.dev.labhive.de)!"
          check_for_duplicate_msg: false

      - name: Discord Bot
        run: |
          curl -X "POST" "${{ secrets.DISCORD_WEBHOOK_PR_DEPLOYMENT }}" \
            -H 'Content-Type: application/json' \
            -d $'{
          "username": "BizzyB",
          "embeds": [
            {
              "author": {
                "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                "name": "GitHub"
              },
              "title": "New Deployment: ${{ github.event.pull_request.title }}",
              "description": "${{ github.event.pull_request.body }}\\n\\nAutomatically deployed to\\nhttps://${BRANCH}.dev.labhive.de",
              "url": "${{ github.event.pull_request.html_url }}"
            }
          ]
          }'
